### ISSUE TITLE
Readme.md update suggestion for --stage flag

### ISSUE THREAD

**Issue by nosvalds** [arielschvartz/serverless-dynamodb-seed#1]
It would be nice to add this to the readme.md to show how to run for a specific stage.

If you want to run for a specific stage:

```bash
$ sls dynamodb:seed --stage stageName
```

**Comment by arielschvartz** [comment]
Thank you very much for the suggestion @nosvalds ! Just fixed it and fixed some other issues in the docs! Now everything is smooth! =)
